#! /bin/bash

cd ~/handsonpython/
rsync -avh   build/html/* ../wmirror/python/hands-on/3.1/handsonHtml/
rsync -avh   changelog.html ../wmirror/python/hands-on/3.1/
rsync -avh   index.html ../wmirror/python/hands-on/3.1/

cp build/latex/Hands-onPythonTutorial.pdf ../wmirror/python/hands-on/3.1/

cd ../wmirror/python/hands-on/3.1/
rm handsonHtml.zip
zip -R handsonHtml.zip handsonHtml/* handsonHtml/*/* 
echo Remember wwwsync\!
