#! /bin/bash

cd ~/handsonpython/examples
rm sample*.txt
rm www/*.txt
rm -R __pycache__
rm -R www/__pycache__
rm www/cgiServerScript
rm www/tempBrowseLocal.html
echo Removed .txt files, cgiServerScript, tempBrowseLocal.html in examples/www

rsync -avh   * ../wmirror/python/hands-on/3.1/examples/
echo examples to wmirror
cd ~/wmirror/python/hands-on/3.1/examples/
rm ../examples.zip
zip ../examples.zip * www/* 
echo remade examples.zip in wmirror

